version: '3.8'

services:
  # https://github.com/prometheus/node_exporter
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    # to enable web.disable-exporter-metrics one has to
    # give all flags because of the way the image was created
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--web.disable-exporter-metrics'
    expose:
      - 9100
    # for testing
    ports:
      - 9100:9100

  telegraf:
    image: library/telegraf:1.28.5-alpine
    restart: unless-stopped
    volumes:
      - ./conf:/etc/telegraf:ro
      # input metrics placed here by cronjobs
      - ./metrics:/metrics:ro
    # this reloads telegraf on config change, but not additions!
    command: "--watch-config poll --debug"
    # this port needs to be opened to access the metrics in prometheus
    ports:
      - 9502:9502
